### ISSUE TITLE
ImportError for python but not for python3

### ISSUE THREAD

**Issue by jingweiz** [shazow/urllib3#1106]
Hi,
when I try to do ```conda``` on my machine Ubuntu14.04, I get the following error:
```
Traceback (most recent call last):
  File "/home/zhang/anaconda2/bin/conda", line 4, in <module>
    import conda.cli
  File "/home/zhang/anaconda2/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/home/zhang/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/home/zhang/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 20, in <module>
    from ..common.url import urlparse, path_to_url
  File "/home/zhang/anaconda2/lib/python2.7/site-packages/conda/common/url.py", line 17, in <module>
    from requests.packages.urllib3.util.url import parse_url
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 92, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named urllib3.packages.ordered_dict
```

When I run ```pip install urllib3``` I get the following:
```
Requirement already satisfied (use --upgrade to upgrade): urllib3 in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```
However,
```
me@mymachine:~$ python
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import urllib3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named urllib3
```

```
me@mymachine:~$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
```
How should I resolve this issue? Thanks in advance!

**Comment by Lukasa** [comment]
This looks like you're mixing packages provided by your distribution with packages provided by `pip`/`conda`. You *must* keep those separate: distributions edit packages in surprising ways you may fail to keep track of. In this case, you have a `requests` that is expecting to look for an unvendored urllib3, but no urllib3 in your envionment.

I don't know how conda manages this, but for `pip` you *must* use a virtualenv if you want to `pip install` anything on Linux. Otherwise, you need to restrict yourself to apt-get.
