### ISSUE TITLE
Reduce reliance on specific TLS/SSL constants

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#1114]
There are a bunch of tests in `test.with_dummyserver.with_https` that rely on having specific OpenSSL constants present (e.g. Some of the ones in TestHTTPS_TLSv1. Ideally these tests would be refactored to be more tolerant of not having some constants around by picking the ones they can get, rather than being specific. 

Related: #1113

**Comment by Lukasa** [comment]
The relevant output data:

```
======================================================================
ERROR: test_set_ssl_version_to_sslv3 (test.with_dummyserver.test_https.TestHTTPS_TLSv1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/test/with_dummyserver/test_https.py", line 425, in test_set_ssl_version_to_sslv3
    self._pool.ssl_version = ssl.PROTOCOL_SSLv3
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

======================================================================
ERROR: test_ssl_version_as_short_string (test.with_dummyserver.test_https.TestHTTPS_TLSv1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/test/with_dummyserver/test_https.py", line 434, in test_ssl_version_as_short_string
    self.assertRaises(SSLError, self._pool.request, 'GET', '/')
  File "/nix/store/s8l7hkhchqwp2sljmz738f3fgi8yrl2k-python-2.7.13/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/connectionpool.py", line 782, in _validate_conn
    conn.connect()
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/connection.py", line 218, in connect
    resolved_ssl_version = resolve_ssl_version(self.ssl_version)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/util/ssl_.py", line 175, in resolve_ssl_version
    res = getattr(ssl, 'PROTOCOL_' + candidate)
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ssl_version_as_string (test.with_dummyserver.test_https.TestHTTPS_TLSv1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/test/with_dummyserver/test_https.py", line 430, in test_ssl_version_as_string
    self.assertRaises(SSLError, self._pool.request, 'GET', '/')
  File "/nix/store/s8l7hkhchqwp2sljmz738f3fgi8yrl2k-python-2.7.13/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/connectionpool.py", line 782, in _validate_conn
    conn.connect()
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/connection.py", line 218, in connect
    resolved_ssl_version = resolve_ssl_version(self.ssl_version)
  File "/tmp/nix-build-python2.7-urllib3-1.12.drv-0/urllib3-1.12/urllib3/util/ssl_.py", line 175, in resolve_ssl_version
    res = getattr(ssl, 'PROTOCOL_' + candidate)
AttributeError: 'module' object has no attribute 'PROTOCOL_PROTOCOL_SSLv3'
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
--------------------- >> end captured logging << ---------------------
```
