### ISSUE TITLE
Failure to match hostname and IP address in Subject Alternate name

### ISSUE THREAD

**Issue by rhmoult** [shazow/urllib3#1180]
Bottom line upfront: 
urllib3.exceptions.SSLError: hostname '192.168.187.150' doesn't match either of 'customhostname.mydomain', '192.168.187.150'

Details:

import urllib3
import certifi
https = urllib3.PoolManager(cert_reqs='CERT_REQUIRED',ca_certs="/etc/ssl/certs/ca-certificates.crt")
URLGET = "https://192.168.187.150"
https.request('GET', URLGET)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/urllib3-dev-py2.7.egg/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-dev-py2.7.egg/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-dev-py2.7.egg/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-dev-py2.7.egg/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: hostname '192.168.187.150' doesn't match either of 'customhostname.mydomain', '192.168.187.150'

**Comment by Lukasa** [comment]
Please install the `ipaddress` module from PyPI: this will allow us to parse IPAddresses safely and so will let us validate the cert.
