### ISSUE TITLE
Running `tox -e gae` is broken on current master

### ISSUE THREAD

**Issue by alexwlchan** [shazow/urllib3#1183]
Extracted from #1182:

```console
$ tox -e gae
GLOB sdist-make: /Users/alexwlchan/repos/urllib3/setup.py
gae inst-nodeps: /Users/alexwlchan/repos/urllib3/.tox/dist/urllib3-dev.zip
gae installed: appdirs==1.4.3,backports.ssl-match-hostname==3.5.0.1,certifi==2017.4.17,coverage==3.7.1,funcsigs==1.0.2,mock==1.3.0,nose==1.3.7,nose-exclude==0.4.1,NoseGAE==0.5.7,packaging==16.8,pbr==3.0.1,pkginfo==1.4.1,pluggy==0.3.1,psutil==4.3.1,py==1.4.33,pyparsing==2.2.0,PySocks==1.5.6,pytest==3.1.0,requests==2.14.2,six==1.10.0,tornado==4.2.1,tox==2.1.1,twine==1.5.0,urllib3===dev,virtualenv==15.1.0
gae runtests: PYTHONHASHSEED='2409600760'
gae runtests: commands[0] | nosetests -c /Users/alexwlchan/repos/urllib3/test/appengine/nose.cfg test/appengine
Traceback (most recent call last):
  File ".tox/gae/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/Users/alexwlchan/repos/urllib3/.tox/gae/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/Users/alexwlchan/repos/urllib3/.tox/gae/lib/python2.7/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/Users/alexwlchan/repos/urllib3/.tox/gae/lib/python2.7/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/Users/alexwlchan/repos/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/Users/alexwlchan/repos/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/alexwlchan/repos/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Users/alexwlchan/repos/urllib3/.tox/gae/lib/python2.7/site-packages/nosegae.py", line 91, in configure
    import dev_appserver
ImportError: No module named dev_appserver
ERROR: InvocationError: '/Users/alexwlchan/repos/urllib3/.tox/gae/bin/nosetests -c /Users/alexwlchan/repos/urllib3/test/appengine/nose.cfg test/appengine'
________________________________________________________________________________ summary _________________________________________________________________________________
ERROR:   gae: commands failed
```

**Comment by alexwlchan** [comment]
Hmm. I found [the most recent successful Travis job](https://travis-ci.org/shazow/urllib3/jobs/236341107), and pinned based on the requirements reported by tox:

```console
$ cat test/appengine/requirements.txt
requests==2.14.2
appdirs==1.4.3
backports.ssl-match-hostname==3.5.0.1
certifi==2017.4.17
coverage==3.7.1
funcsigs==1.0.2
mock==1.3.0
nose==1.3.7
nose-exclude==0.4.1
NoseGAE==0.5.7
packaging==16.8
pbr==3.0.1
pluggy==0.3.1
psutil==4.3.1
py==1.4.33
pyparsing==2.2.0
PySocks==1.5.6
requests==2.14.2
six==1.10.0
tornado==4.2.1
tox==2.1.1
twine==1.5.0
urllib3===dev
virtualenv==15.1.0
```

Same issue.

**Comment by alexwlchan** [comment]
Interesting, this passes on Travis, with a matching set of versions – see https://travis-ci.org/shazow/urllib3/jobs/236925046 – but not on my local machine.

**Comment by alexwlchan** [comment]
But it doesn’t pass in Travis on my fork – https://travis-ci.org/alexwlchan/urllib3/jobs/236924925 – I wonder, is there something dodgy about the Travis cache for urllib3 that’s masking the bug?

**Comment by jonparrott** [comment]
@alexwlchan yes, sending a PR to fix shortly.
