### ISSUE TITLE
KeyError using doc example: cert_reqs='CERT_REQUIRED'

### ISSUE THREAD

**Issue by rasa** [shazow/urllib3#1221]
## Summary 
http://urllib3.readthedocs.io/en/latest/user-guide.html#ssl says to use:
````python
http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED',ca_certs=certifi.where())
````
but only this worked:
````python
http = urllib3.PoolManager(cert_reqs=ssl.CERT_REQUIRED, ca_certs=certifi.where())
````
## Expected Result
No error.
## Actual Result
````python
Traceback (most recent call last):
  File "ex.py", line 74, in get
    r = http.request('GET', url)
  File "c:\python\lib\site-packages\urllib3\request.py", line 66, in request
    **urlopen_kw)
  File "c:\python\lib\site-packages\urllib3\request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "c:\python\lib\site-packages\urllib3\poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "c:\python\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\python\lib\site-packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "c:\python\lib\site-packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "c:\python\lib\site-packages\urllib3\connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "c:\python\lib\site-packages\urllib3\util\ssl_.py", line 270, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "c:\python\lib\site-packages\urllib3\contrib\pyopenssl.py", line 396, in verify_mode
    _stdlib_to_openssl_verify[value],
KeyError: u'CERT_REQUIRED'
````
## Reproduction Steps
See above.
## System Information
````json
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.13"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010006f",
    "version": "17.0.0"
  },
  "requests": {
    "version": "2.18.1"
  },
  "system_ssl": {
    "version": "100020af"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": true
}
````

**Comment by Lukasa** [comment]
Can you please fill out the System Information section? I do not reproduce this on my system.

**Comment by rasa** [comment]
Done. See above.

**Comment by Lukasa** [comment]
Ok, so there were a number of things missing from your report, but the most important one is this: you're on Python 2, and passing a unicode string. Because the string acts as an identifier (that is, because it's not being printed or sent but is purely being used as part of the program), you need to use a native string, not a unicode one. Remove the `u''` from in front of the string and it'll work just fine.

**Comment by rasa** [comment]
Got ha, thanks, and sorry for the noise!
