### ISSUE TITLE
idna encoding UnicodeError when opening connection

### ISSUE THREAD

**Issue by alanhamlett** [shazow/urllib3#1297]
Looks like `urllib3/util/connection.py`, line 60 isn't correctly catching `UnicodeError` when calling `socket.getaddrinfo`?

## System Info

Platform: Windows-10-10.0.16299-SP0
Python: 3.5.1.final.0
Urllib3: 1.22

## Traceback

```
Traceback (most recent call last):
  File "encodings\\idna.py", line 165, in encode
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\api.py", line 107, in send_heartbeats
    verify=not args.nosslverify)
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\requests\\sessions.py", line 555, in post
    return self.request(\'POST\', url, data=data, json=json, **kwargs)
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\requests\\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\requests\\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\requests\\adapters.py", line 440, in send
    timeout=timeout
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\urllib3\\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\urllib3\\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\urllib3\\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\urllib3\\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\packages\\urllib3\\util\\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "socket.py", line 732, in getaddrinfo
UnicodeError: encoding with \'idna\' codec failed (UnicodeError: label empty or too long)
```

**Comment by haikuginger** [comment]
@alanhamlett,

Thanks for putting this in front of us. Since the host in question is failing during DNS resolution, which we pretty much entirely defer to the Python standard library on, I think the appropriate thing to do is to allow the standard library's IDNA-encoding routine to raise the exception it thinks is appropriate.

Usually this happens when the requested URL is malformed in some way. If you can provide the URL that's being requested (for example, by inserting debugging statements into the requesting package), we can take a closer look and verify that's the case. If not, then we can either reopen this issue or help you get to the right place.

**Comment by alanhamlett** [comment]
The url being requested is: `https://api.wakatime.com/api/v1/users/current/heartbeats.bulk`

**Comment by haikuginger** [comment]
@alanhamlett, can you run these commands and let me know what the results are?

```python
>>> from urllib import getproxies
>>> getproxies()
```

**Comment by alanhamlett** [comment]
`importing getproxies` results in an `ImportError`, but adding debug output to `urllib3/util/connection.py` we found `getaddrinfo` was using a misconfigured proxy setting instead of the correct url:

`socket.getaddrinfo('.wakatime.cfg', 80, <AddressFamily.AF_UNSPEC: 0>, <SocketKind.SOCK_STREAM: 1>)`

I'll catch the error outside of urllib3 and show an informative error message including the proxy argument if it's malformed.

Thanks for the help debugging this!
