### ISSUE TITLE
Not handling RemoteDisconnected exceptions

### ISSUE THREAD

**Issue by thomas-neva** [shazow/urllib3#1327]
EDIT: I found a workaround, but it's ugly. Nested try statements to handle a single RemoteDisconnected exception is no bueno. 👎 

So I've been having trouble getting urllib3 to handle RemoteDisconnect exceptions. There's a urllib3.exceptions.ProtocolError raised in handling http.client.RemoteDisconnect type exceptions that I've come across using Python-3.6.3 on Mac OS installed with Anaconda.

I've created a toy server to hang up before sending a response:
https://gist.github.com/thomas-neva/1d706946f9144891204f937e2076b3ad
https://gist.github.com/thomas-neva/a8d945ada3704c43c519f5f734d653c1

and a simple client using urllib3.PoolManager to duplicate the behavior I'm seeing:
https://gist.github.com/thomas-neva/f70f8b656edd5457df75972fab6237eb

Full Traceback for just calling `try_to_handle_remote_disconnect()` outside the try statements in the lastest version of the client gist are provided below. 

Is the need for nested `try:` statements to handle the behavior of PoolManager.requests for RemoteDisconnected exceptions optimal?

```
Thomass-MacBook-Pro:remote_disconnect_server thomaswood$ python simple_client.py
 
Traceback (most recent call last):
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/thomaswood/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/thomaswood/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/thomaswood/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple_client.py", line 20, in <module>
    try_to_handle_remote_disconnect()
  File "simple_client.py", line 13, in try_to_handle_remote_disconnect
    res = pool.request("POST", server, body=req, headers=header)
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/thomaswood/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/thomaswood/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/thomaswood/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/thomaswood/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by sigmavirus24** [comment]
Hi there, what you're seeing is a feature in Python 3. In short, urllib3 has code that looks like this (but which I'm writing from scratch so probably won't match the actual source)

```py
try:
    # make a request
except http.client.RemoteDisconnected as disconnected_err:
    raise urllib3.exceptions.ProtocolError('Connection aborted.', disconnected_err)
```

Python 3 sees this and says

> Hey, this library was handling `http.client.RemoteDisconnected` but it encountered a different error. Perhaps the user should know about both, so let me tell them.

You shouldn't have to have

```py
try:
    pm.urlopen(...)
except http.client.RemoteDisconnected:
    foo()
```

You should only need

```py
try:
    pm.urlopen(...)
except urllib3.exceptions.ProtocolError:
    foo
```

**Comment by thomas-neva** [comment]
Okay. Thanks!
