### ISSUE TITLE
Retry not being applied to ECONNRESET in pyopenssl

### ISSUE THREAD

**Issue by cjw296** [shazow/urllib3#1331]
We have this retry policy in a requests usage of urllib3:
 
```python
from requests import Response, Session
from requests.adapters import HTTPAdapter
from urllib3 import Retry
 
session = Session()
retry_count = 3
retry = Retry(
                total=retry_count,
                read=retry_count,
                connect=retry_count,
                backoff_factor=0.3,
)
adapter = HTTPAdapter(max_retries=retry)
session.mount('http://', adapter)
session.mount('https://', adapter)
```
 
However, `ECONNRESET` such as the following don't appear to be retried:
 
```
Traceback (most recent call last):
--
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
chunked=chunked)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/usr/lib64/python3.6/http/client.py", line 297, in begin
version, status, reason = self._read_status()
File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/lib64/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 296, in recv_into
return self.recv_into(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 285, in recv_into
raise SocketError(str(e))
OSError: (104, 'ECONNRESET')
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
timeout=timeout
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
chunked=chunked)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/usr/lib64/python3.6/http/client.py", line 297, in begin
version, status, reason = self._read_status()
File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/lib64/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 296, in recv_into
return self.recv_into(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 285, in recv_into
raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/awacs_tools/client.py", line 91, in request
response = self.session.request(method, url, timeout=timeout, **kw)
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
```
 
Are we doing something wrong or is this a bug somewhere?

**Comment by sigmavirus24** [comment]
So we [import `socket.error` as `SocketError`](https://github.com/shazow/urllib3/blob/db1c1b6ade859120469c45de479bcac758ab173e/urllib3/connectionpool.py#L7) and then [catch it](https://github.com/shazow/urllib3/blob/db1c1b6ade859120469c45de479bcac758ab173e/urllib3/connectionpool.py#L628) to handle retries with. In our pyopenssl compatibility, we [raise SocketError](https://github.com/shazow/urllib3/blob/db1c1b6ade859120469c45de479bcac758ab173e/urllib3/contrib/pyopenssl.py#L263) after [importing it](https://github.com/shazow/urllib3/blob/db1c1b6ade859120469c45de479bcac758ab173e/urllib3/contrib/pyopenssl.py#L51).

As you can see from your traceback, that *should* be getting handled (the exception is originating in `getresponse()` in `_make_response`). Of course, we have no clue what versions of urllib3 and requests you're using, so perhaps the code we're referencing isn't relevant to that version. Additionally, we have no clue what you're actual request looks like. So there could be several things wrong here:

1. Your versions of those libraries are older than the versions that supported catching this (I don't know those off the top of my head)
2. Your request is using a method not in the whitelist and so this exception is bubbling up

At this point, this is a discussion for [StackOverflow](https://stackoverflow.com) because it's not a bug in urllib3 (or requests).

Cheers,
Ian

**Comment by cjw296** [comment]
@sigmavirus24 - thanks for looking into this, and apologies for not including the version information:

```
$ pip freeze | egrep 'urllib3|requests|pyOpenSSL'
pyOpenSSL==17.3.0
requests==2.18.4
urllib3==1.22
```

As best I can tell, those are either the latest versions or, in the case on pyOpenSSL, new enough that it shouldn't make a difference. I'll try and dig more if I can reproduce...

**Comment by cjw296** [comment]
Still seeing these, and looking more carefully at the traceback I posted above, I'm correctly ending up inside the block for `_is_read_error` at line ~354, but either `_is_method_retryable` is returning `False` or `read` is `False`. I can't follow how either of those case be true given `Retry` instantiation above, any ideas?

I can't actually see how `read` could be `False` unless it was explicitly set to be `False`. What am I missing?

**Comment by ashwiniramamurthy** [comment]
I am seeing a similar issue. Were you able to resolve this?
Also, why does this issue occur : OSError: (104, 'ECONNRESET') ?

**Comment by RomanMelnyk113** [comment]
Same issue. Any news?

**Comment by zoltan-fedor** [comment]
Same here.

**Comment by sethmlarson** [comment]
@Logicalj @RomanMelnyk113 Could you provide the bare minimum to be able to reproduce your issue including Python version, urllib3 version, OS vendor and version, and the minimally reproducible example script that you're seeing the issue with?

**Comment by barth11** [comment]
I have the same issue. Unfortunately I cannot provide part of my code. I use it to get table from a website which is then used and then I no longer use the library. It's one of the set up steps in my code. Then I have different thing which does not include using urllib3.
I have Python 3.7.3, urrllib3 version 1.24.1, i run my code on Raspberry Pi and I tried it on Ubuntu 16.04.6. Both OSs have the same issue 104 but the message is slightly different.
