### ISSUE TITLE
Two different copies of urllib3 don't work interchangeably

### ISSUE THREAD

**Issue by Arfrever** [shazow/urllib3#567]
I use urllib3 1.10.2.

In working copy of Requests:
```
$ rm -r requests/packages/urllib3
$ python2.7 test_requests.py -v
...
======================================================================
ERROR: test_connection_error_invalid_domain (__main__.RequestsTestCase)
Connecting to an unknown domain should raise a ConnectionError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_requests.py", line 307, in test_connection_error_invalid_domain
    requests.get("http://doesnotexist.google.com")
  File "/tmp/requests/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/tmp/requests/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/tmp/requests/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/requests/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/requests/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib64/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib64/python2.7/site-packages/urllib3/util/retry.py", line 226, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

======================================================================
ERROR: test_connection_error_invalid_port (__main__.RequestsTestCase)
Connecting to an invalid port should raise a ConnectionError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_requests.py", line 312, in test_connection_error_invalid_port
    requests.get("http://httpbin.org:1", timeout=1)
  File "/tmp/requests/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/tmp/requests/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/tmp/requests/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/requests/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/requests/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib64/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib64/python2.7/site-packages/urllib3/util/retry.py", line 226, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

----------------------------------------------------------------------
Ran 143 tests in 40.197s

FAILED (errors=2)
```
Problem strangely does not occur when Requests is using its bundled copy of urllib3.

**Comment by shazow** [comment]
So you have two copies of urllib3, one under requests and one vanilla. That means they have two different copies of classes, so things like `isinstance` is going to fail. Ideally, we can be better about duck-typing values to support this better, but it's not a super high priority.

If you're interested in fixing this though, I'd be +1.

**Comment by Arfrever** [comment]
Technically `requests/packages/urllib3` has been deleted and `requests/packages/__init__.py` is magically importing `urllib3` from site-packages...

**Comment by shazow** [comment]
We'd need to know how your magic works, it's possible that Python still thinks it's two different copies. For example, if you try to import the same class using the two different methods, do `classA is classB`.

**Comment by Arfrever** [comment]
```
>>> import requests.packages.urllib3.fields
>>> requests.packages.urllib3.fields
<module 'requests.packages.urllib3.fields' from '/usr/lib64/python2.7/site-packages/urllib3/fields.pyc'>
>>> import urllib3.fields
>>> urllib3.fields
<module 'requests.packages.urllib3.fields' from '/usr/lib64/python2.7/site-packages/urllib3/fields.pyc'>
>>> requests.packages.urllib3.fields is urllib3.fields
True
>>> requests.packages.urllib3.fields.RequestField is urllib3.fields.RequestField
True
```

**Comment by shazow** [comment]
Cool. Next up you'll need to share a code snippet (test?) which shows the failure and how we can reproduce it. :)

**Comment by shazow** [comment]
... Ideally, a failure reproduced with vanilla urllib3. I'm not sure we can reasonably guarantee any cross-compatibility with butchered versions of third-party libraries. :)

**Comment by Lukasa** [comment]
Also ping @sigmavirus24, given that he implemented the magic `__import__` stuff.

**Comment by shazow** [comment]
@Lukasa Which magic `__import__` stuff? (Also should this issue be in requests land? I don't quite now what magic requests does.)

**Comment by Lukasa** [comment]
The answer is *maybe*.

The magic import stuff is to handle the fact that distros will unbundle urllib3 from requests (something something ideological purity something something dynamic linking something). We added it in kennethreitz/requests#2375 with the goal of trying to ensure that stuff doesn't bug out.

Clearly, we didn't entirely succeed. ;)

Yeah, at the moment I'd assume this is a requests bug until proven otherwise.

**Comment by sigmavirus24** [comment]
This doesn't look like one of those problems. Specifically: `TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'`. Either requests is not converting the retries appropriately or there's a bug in urllib3?

**Comment by sigmavirus24** [comment]
So I can reproduce this. The full part (that py.test prints) from the last part of the stack is:

```
self = Retry(total=Retry(total=0, connect=None, read=False, redirect=None), connect=None, read=None, redirect=0), method = 'GET', url = '/', response = None
error = ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x10c54fad0>, 'Connection to 10.255.255.1 timed out. (connect timeout=0.1)')
_pool = <requests.packages.urllib3.connectionpool.HTTPConnectionPool object at 0x10c7d27d0>, _stacktrace = <traceback object at 0x10c500830>

    def increment(self, method=None, url=None, response=None, error=None, _pool=None, _stacktrace=None):
        """ Return a new Retry object with incremented retry counters.

            :param response: A response object, or None, if the server did not
                return a response.
            :type response: :class:`~urllib3.response.HTTPResponse`
            :param Exception error: An error encountered during the request, or
                None if the response was received successfully.

            :return: A new ``Retry`` object.
            """
        if self.total is False and error:
            # Disabled, indicate to re-raise the error.
            raise six.reraise(type(error), error, _stacktrace)

        total = self.total
        if total is not None:
>           total -= 1
E           TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

I think I know where this is coming from and @Lukasa's right that this is the result of the unvendoring, but I don't think there's anything requests can do to fix it. I'm also thoroughly surprised that pip hasn't run into this with their tests. /cc @dstufft

**Comment by sigmavirus24** [comment]
If I debug into `urlopen`, this is what I see:

```py
(Pdb) p Retry
<class 'requests.packages.urllib3.util.retry.Retry'>
(Pdb) p retries
Retry(total=0, connect=None, read=False, redirect=None)
(Pdb) p retries.__class__
<class 'urllib3.util.retry.Retry'>
```

Somehow, the object requests is passing in isn't properly namespaced. I think I might have a fix we can apply in requests in that case.

**Comment by sigmavirus24** [comment]
Yep. Feel free to close this.

**Comment by sigmavirus24** [comment]
See the commit linked above for the fix. ;D

**Comment by shazow** [comment]
@sigmavirus24 Hm, how does that change anything? Weird.

**Comment by shazow** [comment]
OOOH I get it. Fun.
