### ISSUE TITLE
Possible KeyError issue with Python 3.6

### ISSUE THREAD

**Issue by xZise** [shazow/urllib3#680]
As Travis is now using Python 3.6 when using `nightly` we had recently build breakage partially due to a `KeyError` raised inside of `urllib3`. Unfortunately I can't provide something simple to reproduce it, as it only happens (for me) when I do a full test run of pywikibot. Whenever I only tested the parts where the error occurred I got nothing. I'll still try to narrow it down and maybe provide a good test example but I figured you know `urllib3` and might be able to either help me narrow it down or can test it on your own.

```
======================================================================
ERROR: testQueryApiGetter (tests.wikidataquery_tests.TestApiSlowFunctions)
Test that we can actually retreive data and that caching works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/xZise/pywikibot-core/tests/wikidataquery_tests.py", line 252, in testQueryApiGetter
    data = w.query(q)
  File "/home/travis/build/xZise/pywikibot-core/pywikibot/data/wikidataquery.py", line 601, in query
    data = self.getDataFromHost(fullQueryString)
  File "/home/travis/build/xZise/pywikibot-core/pywikibot/data/wikidataquery.py", line 563, in getDataFromHost
    resp = http.fetch(url)
  File "/home/travis/build/xZise/pywikibot-core/pywikibot/comms/http.py", line 359, in fetch
    error_handling_callback(request)
  File "/home/travis/build/xZise/pywikibot-core/pywikibot/comms/http.py", line 276, in error_handling_callback
    raise request.data
  File "/home/travis/build/xZise/pywikibot-core/pywikibot/comms/http.py", line 255, in _http_process
    auth=auth, timeout=timeout, verify=True)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/requests/adapters.py", line 337, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/requests/adapters.py", line 251, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/requests/packages/urllib3/poolmanager.py", line 139, in connection_from_url
    return self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/requests/packages/urllib3/poolmanager.py", line 125, in connection_from_host
    self.pools[pool_key] = pool
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/requests/packages/urllib3/_collections.py", line 66, in __setitem__
    _key, evicted_value = self._container.popitem(last=False)
KeyError: ('https', 'eu.wiktionary.org', 443)
```

See also: https://phabricator.wikimedia.org/T106212 and http://bugs.python.org/issue24667

**Comment by Lukasa** [comment]
I think this *has* to be a stdlib bug.

The action being performed there is a popitem on `OrderedDict`, which explicitly *lacks* a key. The fact that it then throws a `KeyError` makes absolutely no sense, because we've not provided any.

I recommend raising this against the stdlib, because it's clear that under load it is possible to encounter a situation where `popitem` on `OrderedDict` fails.

**Comment by Lukasa** [comment]
(If you do raise this against the stdlib, can you please put a link from here to the issue there? I'd like to track it.)

**Comment by xZise** [comment]
You might be onto something. When looking at `help(collections.OrderedDict.popitem)`, the signature does not mention “last”:

    popitem(...) method of collections.OrderedDict instance

But on Python 3.4.3 the signature mentions both parameters:

    popitem(self, last=True)

Not sure if the general output has been changed and the documentation still uses the latter notation or whether the signature has been changed. I'll look into it and if there is an issue, will open a bug report against Python (I guess you mean that with stdlib) and of course will reference here.

I'm wondering how often this method is called within urllib3. If that is always happening when this line is called or if it succeeds sometimes.

**Comment by xZise** [comment]
Okay I've submitted a bug report now. And as I've described there, it does not always fail and the key looking from the results I got is always the first element in the dict itself.

**Comment by Lukasa** [comment]
Brilliant, thanks. I've added myself to nosy, I'll jump in if it's needed.

**Comment by jayvdb** [comment]
Update: http://bugs.python.org/issue24667 has been fixed for rc1 .

**Comment by shazow** [comment]
:custard:

**Comment by Lukasa** [comment]
\o/ Go team! In that case, I consider this issue fixed. Thanks for pursuing this in the stdlib folks, y'all are beautiful people. :sparkles:
