### ISSUE TITLE
AppEngine tests failing on travis

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#697]
```
Traceback (most recent call last):
  File ".tox/gae/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/opt/python/2.7.9/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nosegae.py", line 91, in configure
    import dev_appserver
ImportError: No module named dev_appserver
ERROR: InvocationError: '/home/travis/build/shazow/urllib3/.tox/gae/bin/nosetests -c /home/travis/build/shazow/urllib3/test/appengine/nose.cfg test/appengine'
```

https://travis-ci.org/shazow/urllib3/jobs/76562407

@jonparrott Could you take a look please?

**Comment by jonparrott** [comment]
The newest version of the cloud sdk no longer includes the app engine sdk. I have code to fix this in another repo, I'll try to fix this tomorrow evening (PST).
