### ISSUE TITLE
'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by SamuelMarks** [shazow/urllib3#738]
```
$ http DELETE :3000/api/foo X-Access-Token:login::789bd965-65c4-4219-a0b5-0137e9b86eef
Traceback (most recent call last):
  File "/usr/local/bin/http", line 7, in <module>
    from httpie.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/usr/local/lib/python2.7/dist-packages/httpie/core.py", line 16, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

Which is strange, because:
```
In [1]: import ssl

In [2]: ssl.PROTOCOL_SSLv23
Out[2]: 2
```

Running Python 2.7.10 under Ubuntu 15.10 x64.

**Comment by SamuelMarks** [comment]
No clue what happened. I [uninstalled all my `pip` packages](http://stackoverflow.com/a/28641862), then ran:
```
sudo -H pip install setuptools pyasn1 jupyter httpie
```

… and now the `http` command is working again. Weird.
