### ISSUE TITLE
travisci epic failing

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#741]
@Lukasa @sigmavirus24 Any idea what's going on?

Example: https://travis-ci.org/shazow/urllib3/jobs/81394938

Seems to happen for every version of Python. Tried bumping versions in #740 but no help.

```
$ tox
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/session.py", line 38, in main
    config = prepare(args)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/session.py", line 26, in prepare
    config = parseconfig(args)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 223, in parseconfig
    parseini(config, inipath)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 676, in __init__
    self.make_envconfig(name, section, reader._subs, config)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 704, in make_envconfig
    res = meth(env_attr.name, env_attr.default)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 839, in getdict
    s = self.getstring(name, None)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 893, in getstring
    x = self._replace(x)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 993, in _replace
    return RE_ITEM_REF.sub(self._replace_match, x)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 989, in _replace_match
    return handler(match)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 913, in _replace_env
    env_list = self.getdict('setenv')
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 839, in getdict
    s = self.getstring(name, None)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 893, in getstring
    x = self._replace(x)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 993, in _replace
    return RE_ITEM_REF.sub(self._replace_match, x)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 989, in _replace_match
    return handler(match)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tox/config.py", line 913, in _replace_env
[... repeat a billion times]
```

**Comment by Lukasa** [comment]
Oooh, recursion from Tox? How weird.

**Comment by Lukasa** [comment]
Is this related to the `{[testenv]deps}` stuff in `gae`?

**Comment by Lukasa** [comment]
Actually, it's more likely to be `{[testenv]setenv]}` stuff, given that `setenv` features prominently in the traceback.

**Comment by shazow** [comment]
Hrm.

**Comment by sigmavirus24** [comment]
So this is actually related to `{env:VAR_NAME:}`. There's a tox bug report for it that I pasted in a different Issue/PR but which shows that this is being worked on upstream and has been acknowledged. `tl;dr` 2.2.x is unusuable for us.

**Comment by shazow** [comment]
Travis seems to have chilled out again, yay.
