### ISSUE TITLE
ca_cert_dir keyword argument may be passed to HTTPConnectionPool by accident.

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#750]
Seems like as part of #701 I missed the `SSL_KEYWORDS` block in `poolmanager.py`. This means that `ca_cert_dir` may accidentally be passed to the `HTTPConnectionPool`.  This leads to the following error when attempting to use `ca_cert_dir` with a `PoolManager` and then making a plaintext HTTP connection:

```
>>> import urllib3
>>> p = urllib3.PoolManager(ca_cert_dir='/usr/local/etc/openssl')
>>> p.urlopen('GET', 'http://http2bin.org/get')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "urllib3/poolmanager.py", line 162, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "urllib3/connectionpool.py", line 548, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "urllib3/connectionpool.py", line 250, in _get_conn
    return conn or self._new_conn()
  File "urllib3/connectionpool.py", line 211, in _new_conn
    strict=self.strict, **self.conn_kw)
  File "urllib3/connection.py", line 121, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'ca_cert_dir'
```

**Comment by Lukasa** [comment]
This should also make sure to update the new tests in #751 to include the ca_cert_dir field.

**Comment by shazow** [comment]
Mmm that is pretty nasty.
