### ISSUE TITLE
test failures related to JSON

### ISSUE THREAD

**Issue by 0-wiz-0** [shazow/urllib3#774]
I've just updated urllib3 in pkgsrc (a packaging system, so all dependencies are installed manually and not using pip or similar).

There are four test failures when running py.test with python-3.5 on NetBSD:

````
===================================================================================== FAILURES ======================================================================================
______________________________________________________________________ TestConnectionPoolTimeouts.test_timeout ______________________________________________________________________

self = <test.with_dummyserver.test_connectionpool.TestConnectionPoolTimeouts testMethod=test_timeout>

    def test_timeout(self):
        # Requests should time out when expected
        block_event = Event()
        ready_event = self.start_basic_handler(block_send=block_event, num=6)
    
        # Pool-global timeout
        timeout = Timeout(read=SHORT_TIMEOUT)
        pool = HTTPConnectionPool(self.host, self.port, timeout=timeout, retries=False)
    
        wait_for_socket(ready_event)
        conn = pool._get_conn()
        self.assertRaises(ReadTimeoutError, pool._make_request, conn, 'GET', '/')
        pool._put_conn(conn)
        block_event.set() # Release request
    
        wait_for_socket(ready_event)
        block_event.clear()
        self.assertRaises(ReadTimeoutError, pool.request, 'GET', '/')
        block_event.set() # Release request
    
        # Request-specific timeouts should raise errors
        pool = HTTPConnectionPool(self.host, self.port, timeout=LONG_TIMEOUT, retries=False)
    
        conn = pool._get_conn()
        wait_for_socket(ready_event)
        now = time.time()
        self.assertRaises(ReadTimeoutError, pool._make_request, conn, 'GET', '/', timeout=timeout)
        delta = time.time() - now
        block_event.set() # Release request
    
>       self.assertTrue(delta < LONG_TIMEOUT, "timeout was pool-level LONG_TIMEOUT rather than request-level SHORT_TIMEOUT")
E       AssertionError: False is not true : timeout was pool-level LONG_TIMEOUT rather than request-level SHORT_TIMEOUT

test/with_dummyserver/test_connectionpool.py:122: AssertionError
------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------
Starting new HTTP connection (1): localhost
Starting new HTTP connection (1): localhost
Resetting dropped connection: localhost
Resetting dropped connection: localhost
Starting new HTTP connection (1): localhost
Starting new HTTP connection (1): localhost
___________________________________________________________________________ TestPoolManager.test_headers ____________________________________________________________________________

self = <test.with_dummyserver.test_poolmanager.TestPoolManager testMethod=test_headers>

    def test_headers(self):
        http = PoolManager(headers={'Foo': 'bar'})
    
        r = http.request('GET', '%s/headers' % self.base_url)
>       returned_headers = json.loads(r.data.decode())

test/with_dummyserver/test_poolmanager.py:134:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/pkg/lib/python3.5/json/__init__.py:319: in loads
    return _default_decoder.decode(s)
/usr/pkg/lib/python3.5/json/decoder.py:339: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <json.decoder.JSONDecoder object at 0x7f7ff45505d8>, s = '<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>', idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
            a JSON document) and return a 2-tuple of the Python
            representation and the index in ``s`` where the document ended.
    
            This can be used to decode a JSON document from a string that may
            have extraneous data at the end.
    
            """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  
/usr/pkg/lib/python3.5/json/decoder.py:357: JSONDecodeError
------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------
Starting new HTTP connection (1): localhost
Starting new HTTP connection (1): localhost
------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------
INFO:urllib3.connectionpool:Starting new HTTP connection (1): localhost
ERROR:tornado.application:Uncaught exception GET /headers (::1)
HTTPServerRequest(protocol='http', host='localhost:64533', method='GET', uri='/headers', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Encoding': 'identity', 'Foo': 'bar', 'Host': 'localhost:64533'})
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 63, in get
    self._call_method()
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 95, in _call_method
    resp = method(req)
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 209, in headers
    return Response(json.dumps(request.headers))
  File "/usr/pkg/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tornado.httputil.HTTPHeaders object at 0x7f7fedb01e98> is not JSON serializable
ERROR:tornado.access:500 GET /headers (::1) 2.06ms
_______________________________________________________________________ TestHTTPProxyManager.test_headerdict ________________________________________________________________________
  
self = <test.with_dummyserver.test_proxy_poolmanager.TestHTTPProxyManager testMethod=test_headerdict>
  
    def test_headerdict(self):
        default_headers = HTTPHeaderDict(a='b')
        proxy_headers = HTTPHeaderDict()
        proxy_headers.add('foo', 'bar')
    
        http = proxy_from_url(
            self.proxy_url,
            headers=default_headers,
            proxy_headers=proxy_headers)
    
        request_headers = HTTPHeaderDict(baz='quux')
        r = http.request('GET', '%s/headers' % self.http_url, headers=request_headers)
>       returned_headers = json.loads(r.data.decode())
  
test/with_dummyserver/test_proxy_poolmanager.py:239:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/pkg/lib/python3.5/json/__init__.py:319: in loads
    return _default_decoder.decode(s)
/usr/pkg/lib/python3.5/json/decoder.py:339: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  
self = <json.decoder.JSONDecoder object at 0x7f7ff45505d8>, s = '<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>', idx = 0
  
    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
            a JSON document) and return a 2-tuple of the Python
            representation and the index in ``s`` where the document ended.
    
            This can be used to decode a JSON document from a string that may
            have extraneous data at the end.
    
            """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  
/usr/pkg/lib/python3.5/json/decoder.py:357: JSONDecodeError
------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------
Starting new HTTP connection (1): localhost
Starting new HTTP connection (1): localhost
------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------
INFO:urllib3.connectionpool:Starting new HTTP connection (1): localhost
ERROR:tornado.application:Uncaught exception GET /headers (::1)
HTTPServerRequest(protocol='http', host='localhost:64520', method='GET', uri='/headers', version='HTTP/1.1', remote_ip='::1', headers={'Accept': '*/*', 'Host': 'localhost:64520', 'Baz': 'quux', 'Accept-Encoding': 'gzip', 'Foo': 'bar', 'Content-Length': '0', 'Connection': 'close'})
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 63, in get
    self._call_method()
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 95, in _call_method
    resp = method(req)
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 209, in headers
    return Response(json.dumps(request.headers))
  File "/usr/pkg/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tornado.httputil.HTTPHeaders object at 0x7f7fedf5b818> is not JSON serializable
ERROR:tornado.access:500 GET /headers (::1) 0.66ms
_________________________________________________________________________ TestHTTPProxyManager.test_headers _________________________________________________________________________
  
self = <test.with_dummyserver.test_proxy_poolmanager.TestHTTPProxyManager testMethod=test_headers>
  
    def test_headers(self):
        http = proxy_from_url(self.proxy_url,headers={'Foo': 'bar'},
                proxy_headers={'Hickory': 'dickory'})
    
        r = http.request_encode_url('GET', '%s/headers' % self.http_url)
>       returned_headers = json.loads(r.data.decode())
  
test/with_dummyserver/test_proxy_poolmanager.py:161:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/pkg/lib/python3.5/json/__init__.py:319: in loads
    return _default_decoder.decode(s)
/usr/pkg/lib/python3.5/json/decoder.py:339: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  
self = <json.decoder.JSONDecoder object at 0x7f7ff45505d8>, s = '<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>', idx = 0
  
    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
            a JSON document) and return a 2-tuple of the Python
            representation and the index in ``s`` where the document ended.
    
            This can be used to decode a JSON document from a string that may
            have extraneous data at the end.
    
            """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  
/usr/pkg/lib/python3.5/json/decoder.py:357: JSONDecodeError
------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------
Starting new HTTP connection (1): localhost
Starting new HTTP connection (1): localhost
------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------
ERROR:tornado.access:500 GET http://localhost:64520/headers (::1) 2.81ms
INFO:urllib3.connectionpool:Starting new HTTP connection (1): localhost
ERROR:tornado.application:Uncaught exception GET /headers (::1)
HTTPServerRequest(protocol='http', host='localhost:64520', method='GET', uri='/headers', version='HTTP/1.1', remote_ip='::1', headers={'Accept': '*/*', 'Host': 'localhost:64520', 'Content-Length': '0', 'Hickory': 'dickory', 'Accept-Encoding': 'gzip', 'Foo': 'bar', 'Connection': 'close'})
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 63, in get
    self._call_method()
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 95, in _call_method
    resp = method(req)
  File "/scratch/www/py-urllib3/work/urllib3-1.14/dummyserver/handlers.py", line 209, in headers
    return Response(json.dumps(request.headers))
  File "/usr/pkg/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/pkg/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tornado.httputil.HTTPHeaders object at 0x7f7fedf45458> is not JSON serializable
ERROR:tornado.access:500 GET /headers (::1) 0.61ms
ERROR:tornado.access:500 GET http://localhost:64520/headers (::1) 2.82ms
================================================================== 4 failed, 303 passed, 7 skipped in 5.79 seconds ==================================================================
*** Error code 1
  
Stop.
````

This is in an ASCII locale, in case it matters.

installed packages:
````
python35-3.5.1
py35-curl-7.19.3.1
py35-expat-3.5.1
py35-setuptools-19.2
py35-backports_abc-0.4
py35-tornado-4.3
py35-pip-7.1.2
py35-pbr-1.8.1
py35-six-1.10.0
py35-mock-1.3.0nb1
py35-nose-1.3.7
py35-py-1.4.30
py35-test-2.8.3
py35-asn1-0.1.9
py35-cffi-1.4.2
py35-cparser-2.14
py35-idna-2.0
py35-cryptography-1.1.2
py35-OpenSSL-0.15.1
py35-ndg_httpsclient-0.4.0
py35-certifi-2015.9.6.2
py35-Socks-1.5.6
````

Please advise if this is just a packaging problem, or if you need more information.

**Comment by Lukasa** [comment]
This appears to be a problem on your end: you aren't abiding by the version requirements in `dev-requirements.txt`. For example, your Tornado is ahead of ours: we're using 4.2.1, while you've installed 4.3 (which I suspect is where most of the JSON errors are coming from). The other problems there are:

- You're missing `nose-exclude`.
- Your `mock` version *may* not be acceptable
- You're missing `coverage`.

Might be worth trying to fix those things up and see how it goes.

**Comment by 0-wiz-0** [comment]
Thanks for the feedback. I've installed nose-exclude and coverage, with no change in output. I cannot install older versions of tornado or mock, so I'll just assume it's tornado's fault for now.
