### ISSUE TITLE
AttributeError on some response

### ISSUE THREAD

**Issue by Cologler** [shazow/urllib3#810]
access url like `http://www.shushuwu.net/top/postdate_1.html` will raise:
`AttributeError: 'bool' object has no attribute 'close'`

**Comment by shazow** [comment]
Hi there. What of urllib3 version? Which platform? How are you calling this url?

Here's it working fine on master:

```python
import urllib3
http = urllib3.PoolManager()
r = http.request('GET', 'http://www.shushuwu.net/top/postdate_1.html')
print(r.status) # == 200
```

Closing for now, happy to re-open if you provide additional information to help us reproduce your problem. :)

**Comment by IcyNoctiluca** [comment]
I've had the same problem. Although it appears this only happens very rarely and not during every web request.

Here is the full output:


`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 297, in read
    data = self._fp.read()
  File "/usr/lib/python3.5/http/client.py", line 461, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.5/http/client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(0 bytes read, 185 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 185 more expected)', IncompleteRead(0 bytes read, 185 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "btcStpMine.py", line 24, in <module>
    response = http.request('GET', addr,)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 69, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 90, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 162, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 572, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 375, in from_httplib
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 137, in __init__
    self._body = self.read(decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 256, in _error_catcher
    self._connection.close()
AttributeError: 'bool' object has no attribute 'close'`

**Comment by SethMichaelLarson** [comment]
Hey @IcyNoctiluca, can you open a new issue as this one is closed. Please provide urllib3 version, Python version, platform, and what code you're running to be able to reproduce this issue.
