### ISSUE TITLE
Tests fail due to missing "socks" dependency

### ISSUE THREAD

**Issue by davidfstr** [shazow/urllib3#824]
#### Repro Steps

```
# (Install Docker from: http://www.docker.com )

# If OS X, start with:
$ docker-machine start default; eval "$(docker-machine env default)"

# If OS X or Linux, continue with:
$ docker run -it ubuntu:trusty  # Ubuntu 14.04 LTS
$$ apt-get update
$$ apt-get install git -y
$$ apt-get install python3-pip -y
$$ pip3 install virtualenv
$$ git clone https://github.com/shazow/urllib3
$$ cd urllib3/
$$ virtualenv venv
$$ source venv/bin/activate
$$ make test
```

#### Output

<https://gist.github.com/davidfstr/b3697cf83b1935f24ef5>

In particular:

```
ERROR: Failure: ImportError (No module named 'socks')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/urllib3/venv/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/urllib3/venv/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/urllib3/venv/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/urllib3/venv/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/urllib3/venv/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/urllib3/venv/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/urllib3/test/contrib/test_socks.py", line 4, in <module>
    from urllib3.contrib import socks
  File "/urllib3/urllib3/contrib/socks.py", line 21, in <module>
    import socks
ImportError: No module named 'socks'
```

#### Notes

Probably some version of PySocks should be declared in `dev-requirements.txt`.

**Comment by shazow** [comment]
I think we used to not run contrib tests by default but we switched that policy recently. Adding PySocks makes sense.

**Comment by sigmavirus24** [comment]
@shazow it would work
