### ISSUE TITLE
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

### ISSUE THREAD

**Issue by wzrd-clss** [shazow/urllib3#832]
I am getting this error that i saw in issue #567 whenever i retry a request. I am using python 2.7.11. i have requests version 2.9.1 installed but i did not install urllib3

```
Traceback (most recent call last):
  File "/home/vagrant/development/demo/api.py", line 223, in make_request
    response = session.post('https://httpbin.org/status/500',data=self.REQUEST_DICT,timeout=15)
  File "/home/vagrant/.virtualenvs/vdemo/lib/python2.7/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/vagrant/.virtualenvs/vdemo/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/.virtualenvs/vdemo/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/.virtualenvs/vdemo/lib/python2.7/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/home/vagrant/.virtualenvs/vdemo/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 657, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/vagrant/.virtualenvs/vdemo/lib/python2.7/site-packages/requests/packages/urllib3/util/retry.py", line 228, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

```

```
import logging
import requests
from requests.packages.urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter
from .exceptions import PaymentError, RequestError, GatewayError
import httplib
import urllib
import xml.dom.minidom

class RetryAdapter(HTTPAdapter):
    def __init__(self, *args, **kwargs):
        super(RetryAdapter, self).__init__(*args, **kwargs)
        method_whitelist=frozenset(['POST','HEAD', 'TRACE', 'GET', 'PUT', 'OPTIONS', 'DELETE'])
        self.max_retries = Retry(total=self.max_retries, backoff_factor=5, status_forcelist=[429, 500, 502, 503], method_whitelist=method_whitelist)

class Base(object):

    def make_request(self, uri):
        session = requests.Session()
        session.mount('https://httpbin.org/status/500', RetryAdapter(max_retries=2))

        try:
            response = session.post('https://httpbin.org/status/500',data=self.REQUEST_DICT,timeout=15)
            response.raise_for_status()

        except requests.exceptions.ConnectionError as e:
            logger.exception(e.message)
            raise GatewayError('Service temporarily unavailable. Please try again')

        except requests.exceptions.HTTPError as e:
            logger.exception(e.message)
            if self.REQUEST_DICT['mode'] == 'query_trans':
                raise GatewayError('Service temporarily unavailable. Please try again')
            else:              
                raise PaymentError('Error getting response from gateway')

        except requests.exceptions.ConnectTimeout as e:
            logger.exception(e.message)
            raise GatewayError('Service temporarily unavailable. Please try again')

        except requests.exceptions.ReadTimeout as e:
            logger.exception(e.message)
            raise GatewayError('Service temporarily unavailable. Please try again')

        except requests.exceptions.RequestException as e:
            logger.exception(e.message)
            raise GatewayError('Service temporarily unavailable. Please try again')            
        except Exception as e:
            logger.exception(e.message)
            raise GatewayError('Service temporarily unavailable. Please try again')

        return response.text
```

**Comment by shazow** [comment]
Please open requests-related bugs in the requests project, not the urllib3 project.

Quickly looking at the code, I suspect it's this line:

```python
self.max_retries = Retry(total=self.max_retries, backoff_factor=5, status_forcelist=[429, 500, 502, 503], method_whitelist=method_whitelist)
```

Note how the `self.max_retries = ...` assignment is the same variable as the `total=self.max_retries` param value. That's supposed to be an int.
