### ISSUE TITLE
Tests fail on multiple platforms (trusty, wily)

### ISSUE THREAD

**Issue by mindw** [shazow/urllib3#889]
Attempted to run tests from master on the following platforms (used vagrant):
* precise64  - pass
* trusty64 native python 2.7.6- fail
* trusty64 python 2.7.11 - fail
* wily64 python 2.7.10 - fail

The above all fail pretty much the same way:
```
py27 runtests: commands[1] | nosetests
SSS......S.............S...........SEEEEE.EEEEEEEE..............EEEEEE...........................E........E..EE.E.Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/urllib3/dummyserver/server.py", line 126, in run
    self.server = self._start_server()
  File "/home/vagrant/urllib3/dummyserver/server.py", line 122, in _start_server
    self.socket_handler(sock)
  File "/home/vagrant/urllib3/test/with_dummyserver/test_socketlevel.py", line 175, in socket_handler
    sock_timeout = listener.accept()[0]
  File "/usr/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
timeout: timed out

..............S..........S..S..........................................SSSEEEEEESEEEEEESEEEEEEEE.EEEEEEEE......................................................................................................................................................................................
```

**Comment by Lukasa** [comment]
Do the same tests fail consistently? Some of these tests are timing sensitive, which can cause problems.

**Comment by mindw** [comment]
They seem to be pretty consistent. All were executed on the same host and method:
* vagrant init xxx -> vagrant up -> vagrant ssh
* install python-dev libssl-dev libffi-dev
* install latest pip/virtualenv
* git clone urllib3
* install tox 2.1.1
* tox -e py27 -r (several times)
