### ISSUE TITLE
Tests fail on Win32

### ISSUE THREAD

**Issue by mindw** [shazow/urllib3#890]
Tested Python 2.7.11 32bit, 3.4.3 64bit, 3.5.1 64bit:
Also PySocks 1.5.7 is broken for Python 2.7.x on windows due to Anorov/PySocks#35.
**2.7.11:**
```
py27 runtests: commands[1] | nosetests
SSSINFO:urllib3.connectionpool:Starting new HTTPS connection (1): localhost
INFO:tornado.access:200 GET / (::1) 2.00ms
DEBUG:urllib3.connectionpool:"GET / HTTP/1.1" 200 13
......E..........E..S........................................................................................................E..........S..S..........................................SSS......S..............................................................................................................................................................................................................
======================================================================
ERROR: test_ca_dir_verified (test.contrib.test_pyopenssl.TestHTTPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 66, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 101, in test_ca_dir_verified
    r = https_pool.request('GET', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
SSLError: ("bad handshake: Error([('PEM routines', 'PEM_read_bio', 'no start line'), ('x509 certificate routines',
'X509_load_cert_file', 'PEM lib'), ('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
urllib3.connectionpool: INFO: Starting new HTTPS connection (2): localhost
tornado.general: WARNING: SSL Error on 948 ('::1', 62950, 0, 0): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown
ca (_ssl.c:590)
tornado.general: ERROR: Uncaught exception
Traceback (most recent call last):
  File "j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages\tornado\http1connection.py", line 693, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages\tornado\http1connection.py", line 168, in _read_message
    quiet_exceptions=iostream.StreamClosedError)
  File "j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: We should rely on the platform CA file to validate authenticity of SSL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 103, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 217, in test_ssl_verified_with_platform_ca_certs
    https_pool.request('HEAD', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): httpbin.org
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ca_dir_verified (test.with_dummyserver.test_https.TestHTTPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 66, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 101, in test_ca_dir_verified
    r = https_pool.request('GET', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
urllib3.connectionpool: INFO: Starting new HTTPS connection (2): localhost
--------------------- >> end captured logging << ---------------------
```

**3.4.3**:
```
SSS......E..........E..S........................................................................................................E..........S..S............................................................................................S.................................................S...................................................................................................................
======================================================================
ERROR: test_ca_dir_verified (test.contrib.test_pyopenssl.TestHTTPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 66, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 101, in test_ca_dir_verified
    r = https_pool.request('GET', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
nose.proxy.SSLError: ("bad handshake: Error([('PEM routines', 'PEM_read_bio', 'no start line'), ('x509 certificate
routines', 'X509_load_cert_file', 'PEM lib'), ('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
urllib3.connectionpool: INFO: Starting new HTTPS connection (2): localhost
tornado.general: WARNING: SSL Error on 920 ('::1', 61257, 0, 0): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown
ca (_ssl.c:600)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: We should rely on the platform CA file to validate authenticity of SSL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 103, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 217, in test_ssl_verified_with_platform_ca_certs
    https_pool.request('HEAD', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
nose.proxy.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): httpbin.org
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ca_dir_verified (test.with_dummyserver.test_https.TestHTTPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 66, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 101, in test_ca_dir_verified
    r = https_pool.request('GET', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
nose.proxy.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
urllib3.connectionpool: INFO: Starting new HTTPS connection (2): localhost
tornado.general: WARNING: SSL Error on 1640 ('::1', 61513, 0, 0): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:600)
```

**3.5.1**:
```
......E..........E..S..........................j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py35\lib\site-packages\nose\util.py:453: DeprecationWarning: inspect.getargspec() is deprecated, use
inspect.signature() instead
  inspect.getargspec(func)
..............................................................................E..........S..S............................................................................................S.................................................S...................................................................................................................
======================================================================
ERROR: test_ca_dir_verified (test.contrib.test_pyopenssl.transplant_class.<locals>.C)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 66, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 101, in test_ca_dir_verified
    r = https_pool.request('GET', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: ("bad handshake: Error([('PEM routines', 'PEM_read_bio', 'no start line'), ('x509 certificate routines', 'X509_load_cert_file', 'PEM lib'), ('SSL routines', 'ssl3_get_server_certificate', 'certificate
verify failed')],)",)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
urllib3.connectionpool: INFO: Starting new HTTPS connection (2): localhost
tornado.general: WARNING: SSL Error on 868 ('::1', 62126, 0, 0): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown
ca (_ssl.c:645)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: We should rely on the platform CA file to validate authenticity of SSL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 103, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 217, in test_ssl_verified_with_platform_ca_certs
    https_pool.request('HEAD', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): httpbin.org
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ca_dir_verified (test.with_dummyserver.test_https.TestHTTPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 66, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 101, in test_ca_dir_verified
    r = https_pool.request('GET', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
urllib3.connectionpool: INFO: Starting new HTTPS connection (2): localhost
tornado.general: WARNING: SSL Error on 1596 ('::1', 62397, 0, 0): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:645)
--------------------- >> end captured logging << ---------------------
```

**Comment by Lukasa** [comment]
I'll need to spin up a Windows VM to dive into this, so unless someone else on the team with access to a Windows box wants to start taking a look soon I'll dive into it on Monday.

**Comment by mindw** [comment]
Please note that using pysocks 1.5.7 things get a lot worse.

**Comment by haikuginger** [comment]
Figured out the `test_ca_dir_verified` issue, I think.

Basically, we're symlinking the individual hashed CA cert files for the dummyserver (`98a2772e.0`, `b6b9ccf9.0`) to the `cacert.pem` file in that directory. But, git on Windows doesn't handle reproducing those symlinks by default, so they're just files containing the filename for `cacert.pem`. As a result, when OpenSSL goes to verify the certificate, there's nothing there.

Possible workarounds for the moment are to copy `cacert.pem` to those filenames, or to manually create the symlink.

**Comment by Lukasa** [comment]
@haikuginger Good spot! Probably best to get rid of the symlink and copy the files into place.

**Comment by haikuginger** [comment]
Agreed. PR in a moment.

**Comment by Lukasa** [comment]
@mindw Mind trying again with the current master?

**Comment by mindw** [comment]
Updated results:
py27:
```
J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git
>tox -e py27 -r
GLOB sdist-make: J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\setup.py
py27 recreate: J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27
py27 installdeps: -rJ:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git/dev-requirements.txt
py27 inst: J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\dist\urllib3-dev.zip
py27 installed: backports.ssl-match-hostname==3.5.0.1,certifi==2016.2.28,coverage==3.7.1,funcsigs==1.0.2,mock==1.3.0,nose==1.3.7,nose-exclude==0.4.1,pbr==1.10.0,pkginfo==1.3.2,pluggy==0.3.1,py==1.4.31,PySocks==1.5.6,requests==2.10.0,six==1.10.0,tornado==4.2.1,tox==2.1.1,twine==1.5.0,urllib3===dev,virtualenv==15.0.2
py27 runtests: PYTHONHASHSEED='813'
py27 runtests: commands[0] | pip install .[socks,secure]
Processing j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git
  Requirement already satisfied (use --upgrade to upgrade): urllib3===dev from file:///J:/dev/workspace/pythonxy-xy-27/src/python/urllib3/__workspace__/urllib3-git in j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages
Collecting pyOpenSSL>=0.13 (from urllib3===dev)
  Using cached pyOpenSSL-16.0.0-py2.py3-none-any.whl
Collecting ndg-httpsclient (from urllib3===dev)
Collecting pyasn1 (from urllib3===dev)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): certifi in j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages (from urllib3===dev)
Requirement already satisfied (use --upgrade to upgrade): PySocks<2.0,>=1.5.6 in j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages (from urllib3===dev)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages (from pyOpenSSL>=0.13->urllib3===dev)
Collecting cryptography>=1.3 (from pyOpenSSL>=0.13->urllib3===dev)
  Using cached cryptography-1.4-cp27-none-win32.whl
Collecting idna>=2.0 (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3===dev)
  Using cached idna-2.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in j:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\.tox\py27\lib\site-packages (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3===dev)
Collecting cffi>=1.4.1 (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3===dev)
  Using cached cffi-1.6.0-cp27-none-win32.whl
Collecting ipaddress (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3===dev)
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting enum34 (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3===dev)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3->pyOpenSSL>=0.13->urllib3===dev)
Building wheels for collected packages: urllib3
  Running setup.py bdist_wheel for urllib3 ... done
  Stored in directory: C:\Users\gabi\AppData\Local\pip\Cache\wheels\3a\31\18\91f1d6a59d8ac4d1c6e27ca9bc58c9a020697731a9c51b2130
Successfully built urllib3
Installing collected packages: pyasn1, idna, pycparser, cffi, ipaddress, enum34, cryptography, pyOpenSSL, ndg-httpsclient
Successfully installed cffi-1.6.0 cryptography-1.4 enum34-1.1.6 idna-2.1 ipaddress-1.0.16 ndg-httpsclient-0.4.1 pyOpenSSL-16.0.0 pyasn1-0.1.9 pycparser-2.14
py27 runtests: commands[1] | nosetests
SSS.................E..S...................................................................................................................S..S..........................................SSS......S..............................................................................................................................................................................................................
======================================================================
ERROR: We should rely on the platform CA file to validate authenticity of SSL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 103, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 217, in test_ssl_verified_with_platform_ca_certs
    https_pool.request('HEAD', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): httpbin.org
--------------------- >> end captured logging << ---------------------
```

py34:
```
SSS.................E..S......................................................................................E............................S..S...........................................................................E................S.................................................S...................................................................................................................
======================================================================
ERROR: We should rely on the platform CA file to validate authenticity of SSL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\__init__.py", line 103, in wrapper
    return test(*args, **kwargs)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_https.py", line 217, in test_ssl_verified_with_platform_ca_certs
    https_pool.request('HEAD', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
nose.proxy.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): httpbin.org
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_timeout_float (test.with_dummyserver.test_connectionpool.TestConnectionPoolTimeouts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_connectionpool.py", line 72, in test_timeout_float
    pool.request('GET', '/')
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\util\retry.py", line 238, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 395, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 315, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
nose.proxy.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=49159): Read timed out. (read timeout=0.001)
-------------------- >> begin captured logging << --------------------
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: INFO: Starting new HTTP connection (2): localhost
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_timeout_errors_cause_retries (test.with_dummyserver.test_socketlevel.TestSocketClosing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\test\with_dummyserver\test_socketlevel.py", line 208, in test_timeout_errors_cause_retries
    response = pool.request('GET', '/', retries=1)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 69,
in request
    **urlopen_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\request.py", line 90,
in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "J:\dev\workspace\pythonxy-xy-27\src\python\urllib3\__workspace__\urllib3-git\urllib3\util\retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
nose.proxy.MaxRetryError: HTTPConnectionPool(host='localhost', port=49520): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=49520): Read timed out. (read timeout=0.001)",))
-------------------- >> begin captured logging << --------------------
urllib3.util.retry: DEBUG: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None)
urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=0, connect=None, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=49520): Read timed out. (read timeout=0.001)",)': /
urllib3.connectionpool: INFO: Starting new HTTP connection (2): localhost
--------------------- >> end captured logging << ---------------------
```

**Comment by Lukasa** [comment]
So those timeout errors I would expect to be transitory: do they regularly reproduce?

The platform CA file is a more interesting failure: that test is clearly invalid on Windows and should simply be skipped. PyOpenSSL *cannot* use the system CA.

**Comment by mindw** [comment]
After digging into this I have trouble understanding the statement above:
* the test explicitly tests the system CA (test_ssl_verified_with_platform_ca_certs)
* wincertstore (or certifi) can be used for this purpose (test passes in both cases) - requests uses certifi.

I'll make a pull request using wincertstore.
Would adding appveyour CI help is detecting such issues in the future?

**Comment by Lukasa** [comment]
The reason I made the statement above and closed #899 is this: the test that is failing here is testing behaviour that does not work on Windows. Specifically, it's testing that we use the certificates from OpenSSL's cert bundle: the ones loaded by `load_default_certs`. 

Those don't exist on Windows! This means that that test cannot pass on Windows. Passing an explicit CA file violates the sprit of that test: it's testing what happens when you *don't* explicitly pass a cert file. 

That test should just be skipped on Windows.

**Comment by mindw** [comment]
OK, I'll make a pull request for skipping this test on windows as you instructed.

Q: The certs/ directory in the OpenSSL repo has been removed - is that the bundle in question?

For the record the test is named and commented **with platform CA**. Me bad for misunderstanding.

```
    def test_ssl_verified_with_platform_ca_certs(self): 
        """
        We should rely on the platform CA file to validate authenticity of SSL
        certificates. Since this file is used by many components of the OS,
        such as curl, apt-get, etc., we decided to not touch it, in order to
        not compromise the security of the OS running the test suite (typically
        urllib3 developer's OS).

        This test assumes that httpbin.org uses a certificate signed by a well
        known Certificate Authority.
        """ 
```

**Comment by Lukasa** [comment]
Yeah, the comment in the test is unclear unless you understand the intent of the test: it's definitely confusing. 

As to your question about the bundle, no. OpenSSL, when shipped on Linux and other similar operating systems, has a compile-time flag that points to a file or directory that contains root certs on that system. That is ideally what we'd use, but OpenSSL has to know how to find them. No such directory exists on Windows, which is why this test makes no sense on that platform.

**Comment by mindw** [comment]
Thanks for clearing this up. I'll cook up the trivial pull request sometime today.

Unrelated, If you can spare a few minutes please take a look at Anorov/PySocks#47 & Anorov/PySocks#48 .
