### ISSUE TITLE
`make test-gae` failed with "ImportError: No module named dev_appserver"

### ISSUE THREAD

**Issue by npcode** [shazow/urllib3#974]
Here is the error:
```
$ source venv/bin/activate 
$ make test-gae
...
GLOB sdist-make: /home/nori/src/urllib3/setup.py
gae inst-nodeps: /home/nori/src/urllib3/.tox/dist/urllib3-dev.zip
gae installed: backports.ssl-match-hostname==3.5.0.1,certifi==2016.8.31,coverage==3.7.1,funcsigs==1.0.2,mock==1.3.0,nose==1.3.7,nose-exclude==0.4.1,NoseGAE==0.5.7,pbr==1.10.0,pkginfo==1.3.2,pluggy==0.3.1,py==1.4.31,PySocks==1.5.6,requests==2.11.1,six==1.10.0,tornado==4.2.1,tox==2.1.1,twine==1.5.0,urllib3===dev,virtualenv==15.0.3
gae runtests: PYTHONHASHSEED='1616590051'
gae runtests: commands[0] | nosetests -c /home/nori/src/urllib3/test/appengine/nose.cfg test/appengine
Traceback (most recent call last):
  File ".tox/gae/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/home/nori/src/urllib3/.tox/gae/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/nori/src/urllib3/.tox/gae/lib/python2.7/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/home/nori/src/urllib3/.tox/gae/lib/python2.7/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/home/nori/src/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/home/nori/src/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/nori/src/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/nori/src/urllib3/.tox/gae/lib/python2.7/site-packages/nosegae.py", line 91, in configure
    import dev_appserver
ImportError: No module named dev_appserver
ERROR: InvocationError: '/home/nori/src/urllib3/.tox/gae/bin/nosetests -c /home/nori/src/urllib3/test/appengine/nose.cfg test/appengine'
__________________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________________
ERROR:   gae: commands failed
```

**Comment by Lukasa** [comment]
@jonparrott, thoughts?

**Comment by jonparrott** [comment]
The `GAE_PYTHONPATH` environment variable has to be set for `nosegae` to work. For example:

```bash
env GAE_PYTHONPATH=/Users/jonparrott/bin/google_appengine make test-gae
```

Perhaps we could update the Makefile to warn / error if its not set?

**Comment by Lukasa** [comment]
That would be a good idea, I'd merge a patch that does that! =)

**Comment by jonparrott** [comment]
Created #975.

**Comment by npcode** [comment]
@jonparrott  I set the variable but still have the problem. Should I install google appengine by myself?

**Comment by npcode** [comment]
I installed google appengine and now it works well. Thanks!
